name: inventorymanagement
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  google_sign_in: ^5.4.0


  cupertino_icons: ^1.0.8
  
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  firebase_analytics: ^11.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "applogo/app_icon.png"

flutter:

  uses-material-design: true
